[meta]
name     = "Favorite Tracks"
author   = "Tamaaa, Headscracher"
category = "Maptool"
version  = "1.0.0"

[script]
imports = [ "Icons.as", "Formatting.as", "Time.as"]
dependencies = [ "NadeoServices" ]